### ISSUE TITLE
dropdown menu(datepicker) will not show up again once click the parent container scrollbar

### ISSUE THREAD

**Issue by LeoFengNY** [arqex/react-datetime#717]
There was a ticket created for this issue: https://github.com/YouCanBookMe/react-datetime/issues/283

The steps to reproduce:
(1) click on the datetime field, the datepicker show up
(2) before click on any date on datepicker,   click on the scrollbar.  the datepick will be closed automatically.
(3) now click on the datetime field, the datepicker will not show up 

I noticed that when click on the scrollbar in step (2), the datetime field still on focus.

**Comment by arqex** [comment]
It should be working ok in v3.0.4. Thanks!

**Comment by LeoFengNY** [comment]
It is still not working after updating from the version "2.16.3" to "^3.0.4".  I tested in all the major browsers including Chrome, IE and firefox.
